export type AccountRecord = {
  password: string;
  folders: string[];
  pages: string[];
};

export const accounts: Record<string, AccountRecord> = {
haiyennt: {
    password: "Hge&geTEg@ge123",
    folders: [
      "tastefulworldzh",
      "feelgoodbeautyzh",
      "worldtravelerszh",
      "culturalwander",
      "gjwmysteries",
      "healthyliving",
      "healthylivingzh",
      "tastefulworld",
      "feelgoodbeauty",
      "worldtravelers",
      "exclusivevisiondaily",
      "freshpickstoday",
      "dailytalktime",
      "beyondheadlinesdaily",
      "gjwplus",
      "beyondtheknown",
      "gjwplussports",
      "gjwplusdocs",
      "gjwplusseries",
      "gjwplusclassics",
      "gjwpluskids",
    ],
    pages: [
      "tastefulworldzh",
      "feelgoodbeautyzh",
      "worldtravelerszh",
      "culturalwander",
      "gjwmysteries",
      "healthyliving",
      "healthylivingzh",
      "tastefulworld",
      "feelgoodbeauty",
      "worldtravelers",
      "exclusivevisiondaily",
      "freshpickstoday",
      "dailytalktime",
      "beyondheadlinesdaily",
      "gjwplus",
      "beyondtheknown",
      "gjwplussports",
      "gjwplusdocs",
      "gjwplusseries",
      "gjwplusclassics",
      "gjwpluskids",
    ],
  },

  minhduc: {
    password: "He&t65eK53",
    folders: [
      "tastefulworldzh",
      "feelgoodbeautyzh",
      "worldtravelerszh",
      "culturalwander",
      "gjwmysteries",
      "healthyliving",
      "healthylivingzh",
      "tastefulworld",
      "feelgoodbeauty",
      "worldtravelers",
      "exclusivevisiondaily",
      "freshpickstoday",
      "dailytalktime",
      "beyondheadlinesdaily",
      "gjwplus",
      "beyondtheknown",
      "gjwplussports",
      "gjwplusdocs",
      "gjwplusseries",
      "gjwplusclassics",
      "gjwpluskids",
    ],
    pages: [
      "tastefulworldzh",
      "feelgoodbeautyzh",
      "worldtravelerszh",
      "culturalwander",
      "gjwmysteries",
      "healthyliving",
      "healthylivingzh",
      "tastefulworld",
      "feelgoodbeauty",
      "worldtravelers",
      "exclusivevisiondaily",
      "freshpickstoday",
      "dailytalktime",
      "beyondheadlinesdaily",
      "gjwplus",
      "beyondtheknown",
      "gjwplussports",
      "gjwplusdocs",
      "gjwplusseries",
      "gjwplusclassics",
      "gjwpluskids",
    ],
  },
  
  hannah: {
    password: "UhgTRg@kg$253",
    folders: [
      "tastefulworldzh",
      "feelgoodbeautyzh",
      "worldtravelerszh",
      "culturalwander",
      "gjwmysteries",
      "healthyliving",
      "healthylivingzh",
      "tastefulworld",
      "feelgoodbeauty",
      "worldtravelers",
      "exclusivevisiondaily",
      "freshpickstoday",
      "dailytalktime",
      "beyondheadlinesdaily",
      "clearviewdaily",
      "viewscopedaily",
      "dailytrendpulse",
      "horizonupdatesshow",
      "flashbrieftoday",
      "everydayvitalityzh",
      "healthyrhythmdaily",
      "renaradar",
      "renaradarzh",
      "lukeinsights",
      "heresthequestion",
      "newsplanetyoungvoice",
      "gjwplus",
      "beyondtheknown",
      "gjwplussports",
      "gjwplusdocs",
      "gjwplusseries",
      "gjwplusclassics",
      "gjwpluskids",
      "gjwdailybrief",
      "freshsharing",
    ],
    pages: [
      "tastefulworldzh",
      "feelgoodbeautyzh",
      "worldtravelerszh",
      "culturalwander",
      "gjwmysteries",
      "healthyliving",
      "healthylivingzh",
      "tastefulworld",
      "feelgoodbeauty",
      "worldtravelers",
      "exclusivevisiondaily",
      "freshpickstoday",
      "dailytalktime",
      "beyondheadlinesdaily",
      "clearviewdaily",
      "viewscopedaily",
      "dailytrendpulse",
      "horizonupdatesshow",
      "flashbrieftoday",
      "everydayvitalityzh",
      "healthyrhythmdaily",
      "renaradar",
      "renaradarzh",
      "lukeinsights",
      "heresthequestion",
      "newsplanetyoungvoice",
      "gjwplus",
      "beyondtheknown",
      "gjwplussports",
      "gjwplusdocs",
      "gjwplusseries",
      "gjwplusclassics",
      "gjwpluskids",
      "gjwdailybrief",
      "freshsharing",
    ],
  },

  karen: {
    password: "jgGTR#kg$93",
    folders: [
      "tastefulworldzh",
      "feelgoodbeautyzh",
      "worldtravelerszh",
      "culturalwander",
      "gjwmysteries",
      "healthyliving",
      "healthylivingzh",
      "tastefulworld",
      "feelgoodbeauty",
      "worldtravelers",
      "exclusivevisiondaily",
      "freshpickstoday",
      "dailytalktime",
      "beyondheadlinesdaily",
      "clearviewdaily",
      "viewscopedaily",
      "dailytrendpulse",
      "horizonupdatesshow",
      "flashbrieftoday",
      "everydayvitalityzh",
      "healthyrhythmdaily",
      "renaradar",
      "renaradarzh",
      "lukeinsights",
      "heresthequestion",
      "newsplanetyoungvoice",
      "gjwplus",
      "beyondtheknown",
      "gjwplussports",
      "gjwplusdocs",
      "gjwplusseries",
      "gjwplusclassics",
      "gjwpluskids",
      "gjwdailybrief",
      "freshsharing",
    ],
    pages: [
      "tastefulworldzh",
      "feelgoodbeautyzh",
      "worldtravelerszh",
      "culturalwander",
      "gjwmysteries",
      "healthyliving",
      "healthylivingzh",
      "tastefulworld",
      "feelgoodbeauty",
      "worldtravelers",
      "exclusivevisiondaily",
      "freshpickstoday",
      "dailytalktime",
      "beyondheadlinesdaily",
      "clearviewdaily",
      "viewscopedaily",
      "dailytrendpulse",
      "horizonupdatesshow",
      "flashbrieftoday",
      "everydayvitalityzh",
      "healthyrhythmdaily",
      "renaradar",
      "renaradarzh",
      "lukeinsights",
      "heresthequestion",
      "newsplanetyoungvoice",
      "gjwplus",
      "beyondtheknown",
      "gjwplussports",
      "gjwplusdocs",
      "gjwplusseries",
      "gjwplusclassics",
      "gjwpluskids",
      "gjwdailybrief",
      "freshsharing",
    ],
  },

  joanne: {
    password: "TygMcK@kf$13",
    folders: [
      "tastefulworldzh",
      "feelgoodbeautyzh",
      "worldtravelerszh",
      "culturalwander",
      "gjwmysteries",
      "healthyliving",
      "healthylivingzh",
      "tastefulworld",
      "feelgoodbeauty",
      "worldtravelers",
      "exclusivevisiondaily",
      "freshpickstoday",
      "dailytalktime",
      "beyondheadlinesdaily",
      "clearviewdaily",
      "viewscopedaily",
      "dailytrendpulse",
      "horizonupdatesshow",
      "flashbrieftoday",
      "everydayvitalityzh",
      "healthyrhythmdaily",
      "renaradar",
      "renaradarzh",
      "lukeinsights",
      "heresthequestion",
      "newsplanetyoungvoice",
      "gjwplus",
      "beyondtheknown",
      "gjwplussports",
      "gjwplusdocs",
      "gjwplusseries",
      "gjwplusclassics",
      "gjwpluskids",
      "gjwdailybrief",
      "freshsharing",
    ],
    pages: [
      "tastefulworldzh",
      "feelgoodbeautyzh",
      "worldtravelerszh",
      "culturalwander",
      "gjwmysteries",
      "healthyliving",
      "healthylivingzh",
      "tastefulworld",
      "feelgoodbeauty",
      "worldtravelers",
      "exclusivevisiondaily",
      "freshpickstoday",
      "dailytalktime",
      "beyondheadlinesdaily",
      "clearviewdaily",
      "viewscopedaily",
      "dailytrendpulse",
      "horizonupdatesshow",
      "flashbrieftoday",
      "everydayvitalityzh",
      "healthyrhythmdaily",
      "renaradar",
      "renaradarzh",
      "lukeinsights",
      "heresthequestion",
      "newsplanetyoungvoice",
      "gjwplus",
      "beyondtheknown",
      "gjwplussports",
      "gjwplusdocs",
      "gjwplusseries",
      "gjwplusclassics",
      "gjwpluskids",
      "gjwdailybrief",
      "freshsharing",
    ],
  },

  ying: {
    password: "HGtYEG$eff@323",
    folders: ["clearviewdaily", "viewscopedaily", "dailytrendpulse"],
    pages: ["clearviewdaily", "viewscopedaily", "dailytrendpulse"],
  },

  ivyzhang: {
    password: "ygeTTge$eff@#24",
    folders: ["everydayvitalityzh", "healthyrhythmdaily"],
    pages: ["everydayvitalityzh", "healthyrhythmdaily"],
  },

  lucywang: {
    password: "GhyTge#rge@87",
    folders: ["horizonupdatesshow", "flashbrieftoday"],
    pages: ["horizonupdatesshow", "flashbrieftoday"],
  },

  serenak: {
    password: "UgeTHGTge@99",
    folders: ["freshsharing"],
    pages: ["freshsharing"],
  },

  athenam: {
    password: "RWesTjhTg23@19",
    folders: ["gjwdailybrief"],
    pages: ["gjwdailybrief"],
  },
  
  demo: {
    password: "123",
    folders: [
      "clearviewdaily",
      "viewscopedaily",
      "dailytrendpulse",
      "flashbrieftoday",
    ],
    pages: [
      "clearviewdaily",
      "viewscopedaily",
      "dailytrendpulse",
      "flashbrieftoday",
    ],
  },
};

export const sanitizeAccount = (username: string, account: AccountRecord) => ({
  username,
  folders: account.folders,
  pages: account.pages,
  isDemo: username === "demo",
});
